### ISSUE TITLE
Specific addresses are not encoded correctly

### ISSUE THREAD

**Issue by wire-witch** [unknownloner/pocsag-encoder#3]
I noticed that addresses where the bit 0x4 is set are not encoded correctly. The bit is always treated as unset. For example, the address 436215 (0b1101010011111110**1**11) is interpreted as 436211 (0b1101010011111110**0**11) and so on. I found the cause of the bug and I have been able to fix it by changing

```
int addressOffset(int address) {
    return (address & 0x3) * FRAME_SIZE;
}
```

to

```
int addressOffset(int address) {
    return (address & 0x7) * FRAME_SIZE;
}
```

**Comment by faithanalog** [comment]
should be good now. i added a test that encodes an all-ones address also (2097151, 0b111111111111111111111)
